name: Trigger Aggregated Update Site Generation

on:
  push:

jobs:
  aggregation:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger aggregated update site generation
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Generate And Deploy
          repo: vitruv-tools/Vitruv-Build-AggregatedUpdateSite
          token: ${{ secrets.UPDATE_SITE_DEPLOY_KEY }}
